/* main.vala.c generated by valac 0.34.7, the Vala compiler
 * generated from main.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>


#define TYPE_MAIN_APP_WINDOW (main_app_window_get_type ())
#define MAIN_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN_APP_WINDOW, MainAppWindow))
#define MAIN_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN_APP_WINDOW, MainAppWindowClass))
#define IS_MAIN_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN_APP_WINDOW))
#define IS_MAIN_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN_APP_WINDOW))
#define MAIN_APP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN_APP_WINDOW, MainAppWindowClass))

typedef struct _MainAppWindow MainAppWindow;
typedef struct _MainAppWindowClass MainAppWindowClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _MainAppWindowPrivate MainAppWindowPrivate;

struct _MainAppWindow {
	GtkWindow parent_instance;
	MainAppWindowPrivate * priv;
};

struct _MainAppWindowClass {
	GtkWindowClass parent_class;
};


static gpointer main_app_window_parent_class = NULL;

void _vala_main (gchar** args, int args_length1);
GType main_app_window_get_type (void) G_GNUC_CONST;
MainAppWindow* main_app_window_new (void);
MainAppWindow* main_app_window_construct (GType object_type);
enum  {
	MAIN_APP_WINDOW_DUMMY_PROPERTY
};
static GObject * main_app_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);


void _vala_main (gchar** args, int args_length1) {
	MainAppWindow* AppWindow = NULL;
	MainAppWindow* _tmp0_ = NULL;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_app_window_new ();
	g_object_ref_sink (_tmp0_);
	AppWindow = _tmp0_;
	gtk_widget_show_all ((GtkWidget*) AppWindow);
	gtk_main ();
	_g_object_unref0 (AppWindow);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}


MainAppWindow* main_app_window_construct (GType object_type) {
	MainAppWindow * self = NULL;
	self = (MainAppWindow*) g_object_new (object_type, NULL);
	return self;
}


MainAppWindow* main_app_window_new (void) {
	return main_app_window_construct (TYPE_MAIN_APP_WINDOW);
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


static GObject * main_app_window_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	MainAppWindow * self;
	parent_class = G_OBJECT_CLASS (main_app_window_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_MAIN_APP_WINDOW, MainAppWindow);
	gtk_window_set_title ((GtkWindow*) self, "EasyCW");
	g_object_set ((GtkWindow*) self, "default-height", 500, NULL);
	g_object_set ((GtkWindow*) self, "default-width", 500, NULL);
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	g_signal_connect ((GtkWidget*) self, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	return obj;
}


static void main_app_window_class_init (MainAppWindowClass * klass) {
	main_app_window_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->constructor = main_app_window_constructor;
}


static void main_app_window_instance_init (MainAppWindow * self) {
}


GType main_app_window_get_type (void) {
	static volatile gsize main_app_window_type_id__volatile = 0;
	if (g_once_init_enter (&main_app_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainAppWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_app_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (MainAppWindow), 0, (GInstanceInitFunc) main_app_window_instance_init, NULL };
		GType main_app_window_type_id;
		main_app_window_type_id = g_type_register_static (gtk_window_get_type (), "MainAppWindow", &g_define_type_info, 0);
		g_once_init_leave (&main_app_window_type_id__volatile, main_app_window_type_id);
	}
	return main_app_window_type_id__volatile;
}



